### ISSUE TITLE
No built in cube, polygon object or any at all

### ISSUE THREAD

**Issue by l0go** [3dreamengine/3DreamEngine#1]
This might take a bit but it is good to have here

**Comment by l0go** [comment]
Test

**Comment by logo4poop** [comment]
Testatestest

**Comment by BenutzerEinsZweiDrei** [comment]
Load
https://github.com/ndmitchell/fossilizer/blob/master/data/tetrahedron.obj
;)

**Comment by Luke100000** [comment]
> 
> 
> Load
> https://github.com/ndmitchell/fossilizer/blob/master/data/tetrahedron.obj
> ;)

Crashes because 3DreamEngine expects normals :)
That would be the converted one. Still not an in built one, ouf.

`
o tetrahedron
v -0.433013 -0.409056 -0.500000
v 0.433013 -0.409056 -0.000000
v -0.433013 -0.409056 0.500000
v -0.144338 0.409056 0.000000
vn 0.0000 -1.0000 -0.0000
vn -0.9430 0.3327 0.0000
vn 0.4715 0.3327 0.8167
vn 0.4715 0.3327 -0.8167
s off
f 1//1 2//1 3//1
f 3//2 4//2 1//2
f 2//3 4//3 3//3
f 1//4 4//4 2//4
`
