### ISSUE TITLE
sunshadow enabled draws strange shadow

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#10]
[https://youtu.be/U2ZC-y04P80](url)

**Comment by Luke100000** [comment]
3Dream is using 3 cascade shadow maps, what you see are pixels out of their range (I will change them to be always lit instead of always shadow). What is the unit you are using? 3Dream is designed to be 1m per unit. You can increase shadow_distance accordingly, but Im not sure if there are further issues when using different unit systems.

**Comment by thisnickwasfree** [comment]
>What is the unit you are using?

Metres.

**Comment by Luke100000** [comment]
> 
> 
> > What is the unit you are using?
> 
> Metres.

1 unit is 1 meter? That should be correct. Could you by chance send me the code so I can take a look on it? By the way I really like the menus paper look!

**Comment by Luke100000** [comment]
I found a potential bug, did the bug disappear?

**Comment by JoshEngebretson** [comment]
I haven't been able to get cascade shadow maps from the sun working in the first person example.  Should this be possible?

**Comment by Luke100000** [comment]
Thanks for the hint, they have been disabled by me and I have no clue why. Also fixed some shadow related bugs.
