### ISSUE TITLE
Frame's parametres (feature request)

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#19]
Does 3dreamengine have a possibility to render smaller frame than love2d project's window has?
It would be nice to create 2d frame with custom width and height (like init.resize function does) at custom coordinates (x and y for left upper corner of the frame).
And yeah, last version had special method for changing camera's fov, but looks like it was removed. That's not a real problem to change this in code, but the method was really useful.

**Comment by Luke100000** [comment]
> 
> 
> Does 3dreamengine have a possibility to render smaller frame than love2d project's window has?
> It would be nice to create 2d frame with custom width and height (like init.resize function does) at custom coordinates (x and y for left upper corner of the frame).
> And yeah, last version had special method for changing camera's fov, but looks like it was removed. That's not a real problem to change this in code, but the method was really useful.

Yes this is implemented and should work, tomorrow I will prepare a small demo to test and showcase how it works and add it to the readme.
Camera fov is now in the camera object, which makes more sense than a general option. Therefore its `dream.cam.fov` now. (For the default camera)

**Comment by Luke100000** [comment]
Ok I have tested everything and it should work (newest commit made things slightly easier):
The dream:init() functions now takes two additional args, width and height, to set the default canvas set resolution. Also supply the correct ones to the resize function if used.
dream:present() works with active transformations, you can transform the output as you need.

If you need a custom shader, enable dream.renderToFinalCanvas and use the output canvas `dream.canvases.final` manually.

If you want several output canvas sets (e.g. because several resolutions) create a canvas set using
```
--postEffects should be true for default outputs
local set = dream:newCanvasSet(width, height, msaa, deferred_lighting, alphaBlendMode, postEffects)

--this is your output
love.graphics.draw(set.final)
```

Since I'm unhappy with the current scene system (high CPU usage) I wait before I write the docu, since this is the same chapter.
