### ISSUE TITLE
UV coordinates for textures added by links

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#21]
Some objects (not all) looses correct UV-coordinates, if the texture loaded not through mtl and path, but through mat and link. I so not know why this happens, but the modeller says that the possible reason is that UV coordinates are far from limits of texture's square in theese models. Sorry, not a specialist in this question.

**Comment by thisnickwasfree** [comment]
Update. All objects with wrong UV have several materals: 3 or 4. All one-material objects rendered fine.

**Comment by Luke100000** [comment]
They only loose the coordinates, not textures?
If they loose the entire material, make sure you load the objects with the "splitMaterials" tag set to true, since only one material at a time can be rendered. Else it will use the first (or the last, I forgot) material. I may make this automatic, because the engine theoretically knows when splitting is necessary, but for now it needs to be set manually.
The UV-coordinated are loaded into with a float and should not have problems with coords beyond the limit. If its a reasonable distance :)
If this does not help please provide me a minimal/full demo so I can take a look at it.

**Comment by thisnickwasfree** [comment]
>They only loose the coordinates, not textures?

Right. They still have textures, all textures are from different materials (so, materials not lost), but UV coordinates become incorrect. Like some default mode of texturing.

>splitMaterials

I use it.

**Comment by thisnickwasfree** [comment]
>If this does not help please provide me a minimal/full demo so I can take a look at it.

I've written a demo.

https://github.com/thisnickwasfree/3dreamengine_tests

**Comment by Luke100000** [comment]
> 
> 
> > If this does not help please provide me a minimal/full demo so I can take a look at it.
> 
> I've written a demo.
> 
> https://github.com/thisnickwasfree/3dreamengine_tests

Ahh! Love loader does not change the wrap mode to repeat (why should it)! But if you use UV coords outside the bounds you need it. 3Dream does this automatically. I do not know how its done properly in love-loader but I changed the code directly to see if it works:
Replace the postProcess function of the resourceKind image with this:
```
    postProcess = function(data)
		local img = love.graphics.newImage(data)
		img:setWrap("repeat", "repeat")
		img:setFilter("nearest")
		return img
    end
```
And now you a) have proper wrapping and b) nearest filtering.
You might also specify mip-mapping since this is not handled by love-loader either.

Details on why this happened: https://love2d.org/wiki/WrapMode
