### ISSUE TITLE
new dithering and tile's edges

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#22]
https://ibb.co/PTY4VP3
https://ibb.co/FK1q3R7

1. Large space between two tiles (left-down corner). All tiles have same size and placed automatically. Blending set to disabled.
2. New version of engine with average/alpha (see no differ between these two): no space at all.

The first variant is rather strange: even without blending this border should not be large than a pixel, I think.

**Comment by Luke100000** [comment]
1) wild guess but I forgot to set alpha to fixed 1 (after threshold) if blending is disabled, causing some interesting stencil effects. Maybe this was the cause. Anyways thanks for the hint :)
2) I assume the mesh is not connected at this edge, therefore the GPU can not fully remove the hole. Theoretically dithering in the old version should look very similar to the new, I only updated the dither pattern to a slightly more random one.
3) "see no differ between these two" Average yields very good results at several layers of materials (optional with refraction). At a single layer it behaves nearly identical to alpha blending. The border is still there but less visible due to blending with the background. The white border on the trees are caused by the interpolating referenced in the other issues I guess. The "white" transparent color, which should not be visible, blends into the tree.

**Comment by thisnickwasfree** [comment]
>I assume the mesh is not connected at this edge
Tiles 5x5 metres. So, the border is between two different meshes. And there is no space between them. I understand why we can see the border, I do not understand why it is so big without blending — best variant for my current project.

>The white border on the trees are caused by the interpolating referenced in the other issues I guess. The "white" transparent color, which should not be visible, blends into the tree.

Yes, that prevents me from using this mode for a while. But in all other cases average/alpha modes are good.

**Comment by Luke100000** [comment]
Does the alpha mode "disabled" still screw up?

**Comment by Luke100000** [comment]
I made an option to disable dither at all and made alpha blending more clear.
