### ISSUE TITLE
Transparent png.

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#4]
Semi-transparent pixels looks strange. Like they have triangle holes.

**Comment by Luke100000** [comment]
Alpha is tricky. You can either not use alpha (default since it can not know if the texture is transparent), then it will dither between 0 and 1 alpha. Or you can use the alpha pipeline by setting material.alpha = true, which is what you want.
If you have the time please send me a screenshot, because the dithering should not produce triangles.

**Comment by thisnickwasfree** [comment]
>the dithering should not produce triangles
Well, yeah… My mistake not triangles…
[https://ibb.co/7JSFRVv](url)
Just noticed this changed in last version of engine: semi-transparent pixels were opaque before.

**Comment by Luke100000** [comment]
Yes the dithering is normal. Either only use 0 or 1 alpha (which is what I suggest in your case) or adjust the shader to your liking, the alpha=true wont work in this case. Earlier versions used a threshold instead of the dithering, but this made no sense.
Proper alpha blending requires z-sorting, which is slow and not always possible.

**Comment by thisnickwasfree** [comment]
One more screenshot:

[https://ibb.co/9nPPHDr](https://ibb.co/9nPPHDr)

Look under the trees.
These artifacts looks worse while camera moving.

So, the current mode with semi-transparent pixels is almost unusable.

Unfortunately, removing semi-transparent pixels from the texture does not help: artifacts still presented, but in lesser quantity.

**Comment by Luke100000** [comment]
The artifacts from under the trees are strange and I do not know what cause them.
Anyways, I implemented the final alpha blending system, you can now choose between 4 methods.
In your case you can try out the "alpha" blend mode, it "should" work.
In future I add per object settings to mix between them.
